# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Broker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 6
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
        cache-dependency-path: broker-service/go.sum
    - name: Install dependencies
      run: |
        cd broker-service && go mod vendor
    - name: Set binary name 
      run: |
        echo "BINARY_VERSION"=1.3.0 >> $GITHUB_ENV
        BINARY_NAME=brokerApp-${{env.BINARY_VERSION}}-${{env.SHA}}
        echo "BINARY_NAME"=$BINARY_NAME >> $GITHUB_ENV
    - name: Build
      run: cd broker-service && env GOOS=linux CGO_ENABLED=0 go build -ldflags "-X main.buildstamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.githash=${{env.BINARY_VERSION}} -X main.version=${{env.BINARY_VERSION}}" -o ${{env.BINARY_NAME}} ./cmd/api
    - name: check
      run: ls -lha broker-service/
    - name: Upload build result for ${{env.BINARY_NAME}}
      uses: actions/upload-artifact@v3
      with:
        name: brokerApp
        path: broker-service/${{env.BINARY_NAME}}
