# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
        cache-dependency-path: broker-service/go.sum
    - name: Install dependencies
      run: |
        cd broker-service && go mod vendor

    - name: Set outputs
      id: vars
      run: echo "binary_version=$(shell git describe --match 'v[0-9]*' --tags --always)" >> $GITHUB_OUTPUT
    - name: Build
      run: cd broker-service && env GOOS=linux CGO_ENABLED=0 go build -ldflags "-X main.version=${{ steps.vars.outputs.sha_short }}" -o 1.3.4 ./cmd/api
